spring:
    datasource:
        name: test
        url: jdbc:mysql://192.168.0.128:3306/nytzj?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
        username: root
        password: Minstone@2020
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        filters: stat
        maxActive: 200
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
rocketmq:
    name-server: 192.168.0.128:9876
    producer:
        group: flow_group
        send-message-timeout: 3000
# 日志输出级别
logging:
    pattern:
        level: info
timer:
    switch: false

